var data = {obj:[{"name":"用户中心","linkto":"1"},{"name":"产品中心","linkto":"2"},{"name":"订单中心","linkto":"3"},{"name":"采购中心","linkto":"4"},{"name":"CRM","linkto":"5"},{"name":"仓储中心","linkto":"6"}]}
var second_navlist = {
	"1":{
		data:[
				{"name":"部门列表","linkurl":"admin/department"},
				{"name":"职位管理","linkurl":"admin/job"},
				{"name":"菜单管理","linkurl":"admin/menu"},
				{"name":"数据管理","linkurl":"admin/element"},
				{"name":"元素管理","linkurl":"admin/element"}
		]
	},
	"2":{
		data:[
			{
				name:"基础设置",
				childnode:[
				{"name":"品类管理","linkurl":"product/base/category"},
				{"name":"属性管理","linkurl":"product/base/attribute"},
				{"name":"国家设置","linkurl":"product/base/country"},
				{"name":"语言设置","linkurl":"product/base/language"},
				{"name":"用户与一级品类关系","linkurl":"product/base/categoryUserRel"},
				{"name":"币种设置","linkurl":"product/base/currency"},
				{"name":"区域设置","linkurl":"product/base/zone"},
				{"name":"敏感词设置","linkurl":"product/base/sensitiveWord"},
				{"name":"部门与地区关系","linkurl":"product/base/departmentZoneRel"}
				]
			},
			{
				name:"产品管理",
				childnode:[
				{"name":"新品管理(广告)","linkurl":"product/manage/new_ad"},
				{"name":"新品排重(排重)","linkurl":"product/manage/new_check"},
				{"name":"新品审核(主管)","linkurl":"product/manage/new_approve"},
				{"name":"产品列表(广告)","linkurl":"product/manage/product_list"},
				{"name":"产品列表(主管助理)","linkurl":"product/manage/supervisor_assistant"},
				{"name":"产品列表","linkurl":"product/manage/dev_list"},
				{"name":"产品细分品类","linkurl":"product/manage/waitAssign"}
				]
			}
		]
	},
	"3":{
		data:[
			{
				name:"基础配置",
				childnode:[
				{"name":"系统类型管理","linkurl":"orders/base/system_type"},
				{"name":"黑名单管理","linkurl":"orders/base/black_list"},
				{"name":"客服区域管理","linkurl":"orders/base/user_zone"},
				{"name":"客户列表","linkurl":"orders/base/customer"},
				{"name":"活动管理","linkurl":"orders/base/activity"},
				{"name":"发货仓管理","linkurl":"orders/base/warehouse"}
				]
			},
			{
				name:"订单管理",
				childnode:[
				{"name":"订单列表","linkurl":"orders/manage/orders"},
				{"name":"退换货管理","linkurl":"orders/manage/order_change"},
				{"name":"问题件管理","linkurl":"orders/manage/order_question"},
				{"name":"区域仓库","linkurl":"orders/manage/zone_warehouse"}
				]
			}
		]
	},
	"4":{
		data:[
			{
				name:"基础设置",
				childnode:[
				{"name":"采购与产品设置","linkurl":"purchase/base/userProductRel"},
				{"name":"采购与事业部设置","linkurl":"purchase/base/userBuDeptRel"}
				]
			},
			{
				name:"采购管理",
				childnode:[
				{"name":"采购需求","linkurl":"purchase/manage/required"},
				{"name":"采购退货管理","linkurl":"purchase/manage/returned"},
				{"name":"采购单管理","linkurl":"purchase/manage/purchase"},
				{"name":"采购明细管理","linkurl":"purchase/manage/purchaseItem"}
				]
			}
		]
	},
	"5":{data:[{name:"客户列表","linkurl":"crm/customers"}]},
	"6":{
		data:[
				{"name":"库存报表","linkurl":"store/inventory"},
				{"name":"库存进销存","linkurl":"store/lnvoicing"},
				{"name":"调拨单管理","linkurl":"store/transfer"},
				{"name":"转寄仓管理","linkurl":"store/forwardwms"}
		]
	}
}