package com.stosz.fsm.exception;

public enum ConfigInvalidType {
	Unknown,
	InvalidXmlFormat,
	StartStateNotFound,
	EndStateNotFound,
	TriggerTargetStateNotExist,
	EndStateCanNotReach,
	CanNotRouteFromStart,
	CanNotReachEnd,
	RoleNotDefined,
	RoleDuplicated,
	StateMustHaveName,
	OperationMustHaveName,
	TriggerEventMustDefine,
	TargetStateMustDefine,
	StateDuplicated,
	OperationDuplicated,
	ObjectClassNotFound,
	ObjectCanNotInitliaze,
	OperationFromStateNull,
	OperationToStateNull,
	OperationDuplicateFromState,
	PluginEmpty,
	PluginClassNotFound,
	PluginCanNotInitialize,
	OperationFromNotExist,
	OperationToNotExist,
	OperationNameSameAsTriggerEvent,
}
